import random,string

def id_generator(size=12, chars=string.ascii_uppercase + string.digits): ##autogenerated id
        return ''.join(random.choice(chars) for _ in range(size))

def password_generator(size=12, chars=string.ascii_uppercase + string.digits+string.ascii_lowercase+string.punctuation):  ##autogenerated password
        return ''.join(random.choice(chars) for _ in range(size))