# Generated by Django 5.1.1 on 2024-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('dob', models.DateField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
