# Generated by Django 5.1.1 on 2024-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_auto_generate_id_remove_otp_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auto_generate',
            table='health_auto_generate',
        ),
        migrations.AlterModelTable(
            name='otp',
            table='health_otp',
        ),
        migrations.AlterModelTable(
            name='register_user',
            table='health_register_user',
        ),
    ]
