# Generated by Django 5.1.1 on 2024-09-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_rename_user_auto_generate_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_generate',
            old_name='phone',
            new_name='email',
        ),
    ]
