# Generated by Django 5.1.1 on 2024-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_rename_phone_auto_generate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='password',
        ),
        migrations.AddField(
            model_name='auto_generate',
            name='hashed_password',
            field=models.CharField(default=3256, max_length=255),
            preserve_default=False,
        ),
    ]
