# Generated by Django 5.1.1 on 2024-09-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_remove_register_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_generate',
            name='hashed_password',
        ),
    ]
