# Generated by Django 5.1.1 on 2024-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_remove_auto_generate_hashed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_generate',
            name='auto_password',
            field=models.CharField(max_length=255),
        ),
    ]
