# Generated by Django 5.1.1 on 2024-10-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_register_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_generate',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
