# Generated by Django 5.1.1 on 2024-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_generate_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_user',
            name='user_type',
            field=models.IntegerField(choices=[(2, 'Patient'), (3, 'Staff'), (4, 'Doctor')], default=1),
            preserve_default=False,
        ),
    ]
