# Generated by Django 5.1.1 on 2024-10-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_remove_register_user_id_alter_register_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_generate',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='email',
            new_name='user',
        ),
    ]
